eureka:
   client:
      register-with-eureka: true
      fetch-registry: true
      serviceUrl:
         defaultZone: http://localhost:8761/eureka/
         #defaultZone: http://172.31.2.38:8761/eureka/
   instance:
      hostname: localhost
